#-------------------------------------------------------------
# Simpliest Manifest File to create Pod with one Container
#
# Copyleft (c) by Skiba evgeniy 2020
#-------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: my-spring-web-and-tomcat
  labels:
    env  : prod
    app  : main
    tier : frontend
    owner: SkibaEvgeniy
spec:
  containers:
    - name: container-spring
      image: sevad/spring-h2-rest:v1.0.1
      ports:
        - containerPort: 8000

    - name: container-tomcat
      image: tomcat:8.5.38
      ports:
        - containerPort: 8080

