#-------------------------------------------------------------
# Simpliest Manifest File to create Pod with few Container
#
# Copyleft (c) by Skiba evgeniy 2020
#-------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: my-spring-web
  labels:
    env  : prod
    app  : main
    tier : frontend
    owner: SkibaEvgeniy
spec:
  containers:
    - name: container-spring
      image: sevad/spring-h2-rest:v1.0.0
      ports:
        - containerPort: 8000

