#-------------------------------------------------------------
# Manifest File to create Deployment with Labels and ReplicaSet
#
# Copyleft (c) by Denis Astahov 2020
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app  : my-k8s-application
    env  : prod
    owner: Evad
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
        - name : cia-web
          image: sevad/spring-h2-rest:v1.0.1
          ports:
            - containerPort: 8000
