#-------------------------------------------------------------
# Manifest File to create Simple Deployment with Labels
#
# Copyleft (c) by Denis Astahov 2020
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-application
spec:
  selector:
    matchLabels:
      project: my-proj
  template:
    metadata:
      labels:
        project: my-proj
    spec:
      containers:
        - name : kgb-web
          image: sevad/spring-h2-rest:v1.0.0
          ports:
            - containerPort: 8000

